"use client";
import { useMemo, useState } from "react";

type Props={locale:string};
type F={maritalStatus:string;spouseCitizenOrPr:string;spouseAccompanying:string;age:string;education:string;hasCanadianCredential:string;canadianCredentialType:string;firstLanguageRecent:string;firstLanguageTest:string;firstSpeaking:string;firstListening:string;firstReading:string;firstWriting:string;secondLanguageTest:string;secondSpeaking:string;secondListening:string;secondReading:string;secondWriting:string;canadianExperience:string;foreignExperience:string;tradeCertificate:string;validJobOffer:string;jobOfferTeer:string;provincialNomination:string;siblingInCanada:string;spouseEducation:string;spouseCanadianExperience:string;spouseLanguageTest:string;spouseSpeaking:string;spouseListening:string;spouseReading:string;spouseWriting:string};
type R={total:number;core:number;spouse:number;transferability:number;additional:number};

type T={title:string;subtitle:string;calculate:string;official:string;result:string;breakdown:string;core:string;spouse:string;transferability:string;additional:string;noScore:string;spouseSection:string;jobOfferNote:string;select:string;yes:string;no:string;q:Record<string,string>};

const OFFICIAL_URL="https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/check-score.html#calculator";
const init:F={maritalStatus:"",spouseCitizenOrPr:"",spouseAccompanying:"",age:"",education:"",hasCanadianCredential:"",canadianCredentialType:"",firstLanguageRecent:"",firstLanguageTest:"",firstSpeaking:"",firstListening:"",firstReading:"",firstWriting:"",secondLanguageTest:"",secondSpeaking:"",secondListening:"",secondReading:"",secondWriting:"",canadianExperience:"",foreignExperience:"",tradeCertificate:"",validJobOffer:"",jobOfferTeer:"",provincialNomination:"",siblingInCanada:"",spouseEducation:"",spouseCanadianExperience:"",spouseLanguageTest:"",spouseSpeaking:"",spouseListening:"",spouseReading:"",spouseWriting:""};

const en:T={title:"Express Entry CRS Calculator",subtitle:"Aligned with official IRCC flow; estimate only.",calculate:"Calculate Score",official:"Open Official Calculator",result:"Estimated CRS Score",breakdown:"Breakdown",core:"Core / Human Capital",spouse:"Spouse Factors",transferability:"Skill Transferability",additional:"Additional Points",noScore:"Please complete required fields.",spouseSection:"Spouse / common-law partner factors",jobOfferNote:"IRCC removed CRS job-offer points on March 25, 2025.",select:"Select...",yes:"Yes",no:"No",q:{maritalStatus:"1) Marital status",spouseCitizenOrPr:"2-i) Is spouse/partner Canadian citizen or PR?",spouseAccompanying:"2-ii) Will spouse/partner accompany you?",age:"3) Age",education:"4) Education",hasCanadianCredential:"4b) Canadian degree/diploma/certificate?",canadianCredentialType:"4c) Canadian education type",firstLanguageRecent:"5-i) Language test less than 2 years old?",firstLanguageTest:"5-ii) First official language test",firstSpeaking:"First language - Speaking",firstListening:"First language - Listening",firstReading:"First language - Reading",firstWriting:"First language - Writing",secondLanguageTest:"5-iii) Second official language test",secondSpeaking:"Second language - Speaking",secondListening:"Second language - Listening",secondReading:"Second language - Reading",secondWriting:"Second language - Writing",canadianExperience:"6-i) Canadian skilled work (10 years)",foreignExperience:"6-ii) Foreign skilled work (10 years)",tradeCertificate:"7) Trade certificate in Canada?",validJobOffer:"8) Valid job offer?",jobOfferTeer:"8a) NOC TEER of offer",provincialNomination:"9) Provincial/Territorial nomination?",siblingInCanada:"10) Sibling in Canada (citizen/PR)?",spouseEducation:"11) Spouse education",spouseCanadianExperience:"12) Spouse Canadian skilled work",spouseLanguageTest:"13-i) Spouse language test",spouseSpeaking:"Spouse - Speaking",spouseListening:"Spouse - Listening",spouseReading:"Spouse - Reading",spouseWriting:"Spouse - Writing"}};
const fa:T={...en,title:"محاسبه‌گر امتیاز CRS اکسپرس اینتری",subtitle:"هم‌راستا با سوالات رسمی IRCC؛ فقط برآورد.",calculate:"محاسبه امتیاز",official:"محاسبه‌گر رسمی دولت کانادا",result:"امتیاز تقریبی CRS",breakdown:"ریز امتیاز",core:"هسته / سرمایه انسانی",spouse:"امتیاز همسر",transferability:"انتقال‌پذیری مهارت",additional:"امتیاز اضافی",noScore:"لطفا فیلدهای ضروری را کامل کنید.",spouseSection:"فاکتورهای همسر",jobOfferNote:"IRCC از 25 مارس 2025 امتیاز جاب‌آفر را از CRS حذف کرده است.",select:"انتخاب کنید...",yes:"بله",no:"خیر",q:{...en.q,maritalStatus:"1) وضعیت تاهل",spouseCitizenOrPr:"2-i) آیا همسر/پارتنر شهروند یا PR کاناداست؟",spouseAccompanying:"2-ii) آیا همسر/پارتنر همراه شماست؟",age:"3) سن",education:"4) تحصیلات",hasCanadianCredential:"4b) مدرک/دیپلم کانادایی دارید؟",canadianCredentialType:"4c) نوع تحصیل کانادایی",firstLanguageRecent:"5-i) آزمون زبان کمتر از 2 سال؟",firstLanguageTest:"5-ii) آزمون زبان رسمی اول",secondLanguageTest:"5-iii) آزمون زبان رسمی دوم",canadianExperience:"6-i) سابقه کار تخصصی کانادا",foreignExperience:"6-ii) سابقه کار تخصصی خارج کانادا",tradeCertificate:"7) گواهی فنی کانادا دارید؟",validJobOffer:"8) جاب‌آفر معتبر دارید؟",jobOfferTeer:"8a) TEER جاب‌آفر",provincialNomination:"9) نامینیشن استانی/قلمرویی دارید؟",siblingInCanada:"10) خواهر/برادر شهروند یا PR کانادا دارید؟",spouseEducation:"11) تحصیلات همسر",spouseCanadianExperience:"12) سابقه کار تخصصی همسر در کانادا",spouseLanguageTest:"13-i) آزمون زبان همسر",firstSpeaking:"زبان اول - اسپیکینگ",firstListening:"زبان اول - لیسنینگ",firstReading:"زبان اول - ریدینگ",firstWriting:"زبان اول - رایتینگ",secondSpeaking:"زبان دوم - اسپیکینگ",secondListening:"زبان دوم - لیسنینگ",secondReading:"زبان دوم - ریدینگ",secondWriting:"زبان دوم - رایتینگ",spouseSpeaking:"همسر - اسپیکینگ",spouseListening:"همسر - لیسنینگ",spouseReading:"همسر - ریدینگ",spouseWriting:"همسر - رایتینگ"}};
const fr:T={...en,title:"Calculateur CRS Entrée express",subtitle:"Aligné avec le flux officiel IRCC; estimation seulement.",calculate:"Calculer",official:"Calculateur officiel du Canada",result:"Score CRS estimé",breakdown:"Répartition",spouse:"Facteurs du conjoint",noScore:"Veuillez compléter les champs requis.",spouseSection:"Facteurs du conjoint",select:"Sélectionner...",yes:"Oui",no:"Non",q:{...en.q,maritalStatus:"1) État matrimonial",spouseCitizenOrPr:"2-i) Conjoint citoyen/PR du Canada?",spouseAccompanying:"2-ii) Conjoint vous accompagne?",age:"3) Âge",education:"4) Niveau d'études",hasCanadianCredential:"4b) Diplôme/certificat canadien?",canadianCredentialType:"4c) Type d'études canadiennes",firstLanguageRecent:"5-i) Résultats de langue < 2 ans?",firstLanguageTest:"5-ii) Test de première langue",secondLanguageTest:"5-iii) Test de deuxième langue",canadianExperience:"6-i) Expérience qualifiée au Canada",foreignExperience:"6-ii) Expérience qualifiée à l'étranger",tradeCertificate:"7) Certificat de qualification au Canada?",validJobOffer:"8) Offre d'emploi valide?",jobOfferTeer:"8a) TEER de l'offre",provincialNomination:"9) Désignation provinciale/territoriale?",siblingInCanada:"10) Frère/soeur au Canada (citoyen/PR)?",spouseEducation:"11) Études du conjoint",spouseCanadianExperience:"12) Expérience du conjoint au Canada",spouseLanguageTest:"13-i) Test de langue du conjoint",firstSpeaking:"Langue 1 - Expression orale",firstListening:"Langue 1 - Compréhension orale",firstReading:"Langue 1 - Lecture",firstWriting:"Langue 1 - Écriture",secondSpeaking:"Langue 2 - Expression orale",secondListening:"Langue 2 - Compréhension orale",secondReading:"Langue 2 - Lecture",secondWriting:"Langue 2 - Écriture",spouseSpeaking:"Conjoint - Expression orale",spouseListening:"Conjoint - Compréhension orale",spouseReading:"Conjoint - Lecture",spouseWriting:"Conjoint - Écriture"}};

const marital=[{value:"",en:"Select...",fa:"انتخاب کنید...",fr:"Sélectionner..."},{value:"annulled",en:"Annulled Marriage",fa:"ازدواج باطل‌شده",fr:"Mariage annulé"},{value:"commonLaw",en:"Common-Law",fa:"زندگی مشترک",fr:"Union de fait"},{value:"divorced",en:"Divorced / Separated",fa:"مطلقه / جدا",fr:"Divorcé(e)/séparé(e)"},{value:"legallySeparated",en:"Legally Separated",fa:"جدایی قانونی",fr:"Séparé(e) légalement"},{value:"married",en:"Married",fa:"متاهل",fr:"Marié(e)"},{value:"single",en:"Single",fa:"مجرد",fr:"Célibataire"},{value:"widowed",en:"Widowed",fa:"بیوه",fr:"Veuf/Veuve"}];

const yn=(t:T)=>[{value:"",label:t.select},{value:"no",label:t.no},{value:"yes",label:t.yes}];
const edu=(t:T)=>[{value:"",label:t.select},{value:"none",label:"None / less than secondary"},{value:"secondary",label:"Secondary diploma"},{value:"oneYear",label:"One-year post-secondary"},{value:"twoYear",label:"Two-year post-secondary"},{value:"bachelor",label:"Bachelor or 3+ years"},{value:"twoOrMore",label:"Two+ credentials"},{value:"master",label:"Master/professional"},{value:"phd",label:"PhD"}];
const canEdu=(t:T)=>[{value:"",label:t.select},{value:"secondary",label:"Secondary or less"},{value:"oneOrTwoYear",label:"One- or two-year"},{value:"threeOrMore",label:"Three years+ / master / PhD"}];
const tests=(t:T)=>[{value:"",label:t.select},{value:"celpip",label:"CELPIP-G"},{value:"ielts",label:"IELTS"},{value:"pte",label:"PTE Core"},{value:"tef",label:"TEF Canada"},{value:"tcf",label:"TCF Canada"}];
const levels=(t:T)=>[{value:"",label:t.select},{value:"l1",label:"Level 1"},{value:"l2",label:"Level 2"},{value:"l3",label:"Level 3"},{value:"l4",label:"Level 4"},{value:"l5",label:"Level 5"},{value:"l6",label:"Level 6"},{value:"l7",label:"Level 7"},{value:"l8",label:"Level 8"},{value:"l9",label:"Level 9"},{value:"l10",label:"Level 10+"}];
const exp=(t:T,short=false)=>[{value:"",label:t.select},{value:"none",label:"None or <1 year"},{value:"1",label:"1 year"},{value:"2",label:"2 years"},{value:"3",label:short?"3+ years":"3 years"},...(short?[]:[{value:"4",label:"4 years"},{value:"5",label:"5+ years"}])];
const teer=(t:T)=>[{value:"",label:t.select},{value:"major00",label:"NOC TEER 0 Major Group 00"},{value:"otherSkilled",label:"NOC TEER 0(other),1,2,3"},{value:"teer45",label:"NOC TEER 4 or 5"}];

const n=(v:string)=>{const m=/^l(\d+)$/.exec(v);return m?Number(m[1]):0};
const e=(v:string)=>v&&v!=="none"?Number(v):0;
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
const age=(a:number,s:boolean)=>{if(!Number.isFinite(a)||a<17)return 0;if(s){if(a>=20&&a<=29)return 100;return({18:90,19:95,30:95,31:90,32:85,33:80,34:75,35:70,36:65,37:60,38:55,39:50,40:45,41:35,42:25,43:15,44:5}as Record<number,number>)[a]??0;}if(a>=20&&a<=29)return 110;return({18:99,19:105,30:105,31:99,32:94,33:88,34:83,35:77,36:72,37:66,38:61,39:55,40:50,41:39,42:28,43:17,44:6}as Record<number,number>)[a]??0;};
const ed=(v:string,s:boolean)=>((s?{none:0,secondary:28,oneYear:84,twoYear:91,bachelor:112,twoOrMore:119,master:126,phd:140}:{none:0,secondary:30,oneYear:90,twoYear:98,bachelor:120,twoOrMore:128,master:135,phd:150})as Record<string,number>)[v]??0;
const l1=(c:number,s:boolean)=>c<=4?0:c===5?6:c===6?(s?8:9):c===7?(s?16:17):c===8?(s?22:23):c===9?(s?29:31):32+(s?0:2);
const l2=(c:number)=>c<=4?0:c<=6?1:c<=8?3:6;
const cexp=(v:string,s:boolean)=>((s?{none:0,"1":35,"2":46,"3":56,"4":63,"5":70}:{none:0,"1":40,"2":53,"3":64,"4":72,"5":80})as Record<string,number>)[v]??0;
const sed=(v:string)=>({none:0,secondary:2,oneYear:6,twoYear:7,bachelor:8,twoOrMore:9,master:10,phd:10}as Record<string,number>)[v]??0;
const sl=(c:number)=>c<=4?0:c<=6?1:c<=8?3:5;
const scexp=(v:string)=>({none:0,"1":5,"2":7,"3":8,"4":9,"5":10}as Record<string,number>)[v]??0;
const tier=(v:string)=>v==="oneYear"||v==="twoYear"?"short":["bachelor","twoOrMore","master","phd"].includes(v)?"long":"none";
function transfer(eduV:string,first:number[],fx:number,cx:number,trade:string){const min=Math.min(...first),a7=first.every(v=>v>=7),a9=first.every(v=>v>=9),t=tier(eduV);let el=0;if(t!=="none"){if(a9)el=t==="long"?50:25;else if(a7)el=t==="long"?25:13;}let ec=0;if(t!=="none"){if(cx>=2)ec=t==="long"?50:25;else if(cx===1)ec=t==="long"?25:13;}let fl=0;if(fx>=3){if(a9)fl=50;else if(a7)fl=25;}else if(fx>=1){if(a9)fl=25;else if(a7)fl=13;}let fc=0;if(fx>=3){if(cx>=2)fc=50;else if(cx===1)fc=25;}else if(fx>=1){if(cx>=2)fc=25;else if(cx===1)fc=13;}let tl=0;if(trade==="yes"){if(a7)tl=50;else if(min>=5)tl=25;}return clamp(el+ec+fl+fc+tl,0,100);}
const frAdd=(first:number[],second:number[])=>{const a=Math.min(...first),b=Math.min(...second);if(a>=7&&b>=5)return 50;if(a>=7)return 25;return 0;};
function calc(f:F):R|null{const married=f.maritalStatus==="married"||f.maritalStatus==="commonLaw";const withSpouse=married&&f.spouseAccompanying==="yes"&&f.spouseCitizenOrPr!=="yes";const a=Number(f.age);const first=[f.firstSpeaking,f.firstListening,f.firstReading,f.firstWriting].map(n);if(!Number.isFinite(a)||a<=0||!f.education||!f.canadianExperience||first.some(x=>x===0))return null;const second=[f.secondSpeaking,f.secondListening,f.secondReading,f.secondWriting].map(n);const secondAny=second.some(x=>x>0);const firstPts=first.reduce((s,v)=>s+l1(v,withSpouse),0);const secondPts=clamp(second.reduce((s,v)=>s+l2(v),0),0,withSpouse?22:24);const core=age(a,withSpouse)+ed(f.education,withSpouse)+clamp(firstPts+secondPts,0,withSpouse?150:160)+cexp(f.canadianExperience,withSpouse);const spouse=withSpouse?clamp(sed(f.spouseEducation)+scexp(f.spouseCanadianExperience)+[f.spouseSpeaking,f.spouseListening,f.spouseReading,f.spouseWriting].map(n).reduce((s,v)=>s+sl(v),0),0,40):0;const tr=transfer(f.education,first,e(f.foreignExperience),e(f.canadianExperience),f.tradeCertificate);let add=0;if(f.provincialNomination==="yes")add+=600;if(f.siblingInCanada==="yes")add+=15;if(f.hasCanadianCredential==="yes"){if(f.canadianCredentialType==="threeOrMore")add+=30;else if(f.canadianCredentialType==="oneOrTwoYear")add+=15;}if(f.firstLanguageTest==="tef"||f.firstLanguageTest==="tcf")add+=frAdd(first,secondAny?second:[0,0,0,0]);else if(f.secondLanguageTest==="tef"||f.secondLanguageTest==="tcf")add+=frAdd(second,first);const total=core+spouse+tr+add;return{total,core,spouse,transferability:tr,additional:add};}

function S({label,name,value,options,onChange,isRTL}:{label:string;name:keyof F;value:string;options:Array<{value:string;label:string}>;onChange:(name:keyof F,value:string)=>void;isRTL:boolean;}){return(<div><label className={`mb-2 block text-sm font-medium text-slate-700 ${isRTL?"text-right":"text-left"}`}>{label}</label><select name={name} value={value} onChange={(e)=>onChange(name,e.target.value)} className="w-full rounded-xl border border-slate-300 px-4 py-3 outline-none transition focus:border-blue-600">{options.map((o)=><option key={`${name}-${o.value||"e"}`} value={o.value}>{o.label}</option>)}</select></div>);}

export default function ExpressEntryCalculator({locale}:Props){const [f,setF]=useState<F>(init);const [r,setR]=useState<R|null>(null);const [err,setErr]=useState(false);const t=useMemo(()=>locale==="fa"?fa:locale==="fr"?fr:en,[locale]);const isRTL=locale==="fa";const ws=(f.maritalStatus==="married"||f.maritalStatus==="commonLaw")&&f.spouseAccompanying==="yes"&&f.spouseCitizenOrPr!=="yes";const ch=(name:keyof F,value:string)=>setF(p=>({...p,[name]:value}));const run=()=>{const x=calc(f);setR(x);setErr(!x)};const lv=levels(t);
return(<section className="bg-slate-50 py-16"><div className="mx-auto max-w-6xl px-6 lg:px-8"><div className="rounded-3xl bg-white p-8 shadow-sm ring-1 ring-slate-200 md:p-10"><div className={isRTL?"text-right":"text-left"}><h2 className="text-2xl font-bold text-slate-900">{t.title}</h2><p className="mt-3 text-slate-600">{t.subtitle}</p></div>
<div className="mt-8 grid gap-6 md:grid-cols-2">
<S label={t.q.maritalStatus} name="maritalStatus" value={f.maritalStatus} onChange={ch} isRTL={isRTL} options={marital.map(m=>({value:m.value,label:locale==="fa"?m.fa:locale==="fr"?m.fr:m.en}))}/>
<S label={t.q.spouseCitizenOrPr} name="spouseCitizenOrPr" value={f.spouseCitizenOrPr} onChange={ch} isRTL={isRTL} options={yn(t)}/>
<S label={t.q.spouseAccompanying} name="spouseAccompanying" value={f.spouseAccompanying} onChange={ch} isRTL={isRTL} options={yn(t)}/>
<div><label className={`mb-2 block text-sm font-medium text-slate-700 ${isRTL?"text-right":"text-left"}`}>{t.q.age}</label><input name="age" inputMode="numeric" value={f.age} onChange={(e)=>ch("age",e.target.value)} className="w-full rounded-xl border border-slate-300 px-4 py-3 outline-none transition focus:border-blue-600" placeholder="18"/></div>
<S label={t.q.education} name="education" value={f.education} onChange={ch} isRTL={isRTL} options={edu(t)}/><S label={t.q.hasCanadianCredential} name="hasCanadianCredential" value={f.hasCanadianCredential} onChange={ch} isRTL={isRTL} options={yn(t)}/><S label={t.q.canadianCredentialType} name="canadianCredentialType" value={f.canadianCredentialType} onChange={ch} isRTL={isRTL} options={canEdu(t)}/><S label={t.q.firstLanguageRecent} name="firstLanguageRecent" value={f.firstLanguageRecent} onChange={ch} isRTL={isRTL} options={yn(t)}/><S label={t.q.firstLanguageTest} name="firstLanguageTest" value={f.firstLanguageTest} onChange={ch} isRTL={isRTL} options={tests(t)}/><S label={t.q.firstSpeaking} name="firstSpeaking" value={f.firstSpeaking} onChange={ch} isRTL={isRTL} options={lv}/><S label={t.q.firstListening} name="firstListening" value={f.firstListening} onChange={ch} isRTL={isRTL} options={lv}/><S label={t.q.firstReading} name="firstReading" value={f.firstReading} onChange={ch} isRTL={isRTL} options={lv}/><S label={t.q.firstWriting} name="firstWriting" value={f.firstWriting} onChange={ch} isRTL={isRTL} options={lv}/><S label={t.q.secondLanguageTest} name="secondLanguageTest" value={f.secondLanguageTest} onChange={ch} isRTL={isRTL} options={tests(t)}/><S label={t.q.secondSpeaking} name="secondSpeaking" value={f.secondSpeaking} onChange={ch} isRTL={isRTL} options={lv}/><S label={t.q.secondListening} name="secondListening" value={f.secondListening} onChange={ch} isRTL={isRTL} options={lv}/><S label={t.q.secondReading} name="secondReading" value={f.secondReading} onChange={ch} isRTL={isRTL} options={lv}/><S label={t.q.secondWriting} name="secondWriting" value={f.secondWriting} onChange={ch} isRTL={isRTL} options={lv}/><S label={t.q.canadianExperience} name="canadianExperience" value={f.canadianExperience} onChange={ch} isRTL={isRTL} options={exp(t)}/><S label={t.q.foreignExperience} name="foreignExperience" value={f.foreignExperience} onChange={ch} isRTL={isRTL} options={exp(t,true)}/><S label={t.q.tradeCertificate} name="tradeCertificate" value={f.tradeCertificate} onChange={ch} isRTL={isRTL} options={yn(t)}/>
<div className="md:col-span-2 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900">{t.jobOfferNote}</div>
<S label={t.q.validJobOffer} name="validJobOffer" value={f.validJobOffer} onChange={ch} isRTL={isRTL} options={yn(t)}/><S label={t.q.jobOfferTeer} name="jobOfferTeer" value={f.jobOfferTeer} onChange={ch} isRTL={isRTL} options={teer(t)}/><S label={t.q.provincialNomination} name="provincialNomination" value={f.provincialNomination} onChange={ch} isRTL={isRTL} options={yn(t)}/><S label={t.q.siblingInCanada} name="siblingInCanada" value={f.siblingInCanada} onChange={ch} isRTL={isRTL} options={yn(t)}/>
{ws&&<><div className={`md:col-span-2 rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm font-semibold ${isRTL?"text-right":"text-left"}`}>{t.spouseSection}</div><S label={t.q.spouseEducation} name="spouseEducation" value={f.spouseEducation} onChange={ch} isRTL={isRTL} options={edu(t)}/><S label={t.q.spouseCanadianExperience} name="spouseCanadianExperience" value={f.spouseCanadianExperience} onChange={ch} isRTL={isRTL} options={exp(t)}/><S label={t.q.spouseLanguageTest} name="spouseLanguageTest" value={f.spouseLanguageTest} onChange={ch} isRTL={isRTL} options={tests(t)}/><S label={t.q.spouseSpeaking} name="spouseSpeaking" value={f.spouseSpeaking} onChange={ch} isRTL={isRTL} options={lv}/><S label={t.q.spouseListening} name="spouseListening" value={f.spouseListening} onChange={ch} isRTL={isRTL} options={lv}/><S label={t.q.spouseReading} name="spouseReading" value={f.spouseReading} onChange={ch} isRTL={isRTL} options={lv}/><S label={t.q.spouseWriting} name="spouseWriting" value={f.spouseWriting} onChange={ch} isRTL={isRTL} options={lv}/></>}
</div>
<div className={`mt-8 flex flex-wrap gap-3 ${isRTL?"justify-end":"justify-start"}`}><button onClick={run} className="inline-flex rounded-xl bg-slate-900 px-8 py-3 text-sm font-semibold text-white transition hover:bg-slate-800">{t.calculate}</button><a href={OFFICIAL_URL} target="_blank" rel="noopener noreferrer" className="inline-flex rounded-xl bg-blue-600 px-8 py-3 text-sm font-semibold text-white transition hover:bg-blue-700">{t.official}</a></div>
{err&&!r&&<p className={`mt-4 text-sm font-medium text-rose-700 ${isRTL?"text-right":"text-left"}`}>{t.noScore}</p>}
{r&&<div className={`mt-8 rounded-2xl bg-emerald-50 p-6 ring-1 ring-emerald-200 ${isRTL?"text-right":"text-left"}`}><p className="text-sm font-semibold uppercase tracking-[0.14em] text-emerald-700">{t.result}</p><p className="mt-2 text-4xl font-bold text-slate-900">{r.total}</p><p className="mt-5 text-sm font-semibold uppercase tracking-[0.12em] text-slate-500">{t.breakdown}</p><div className="mt-3 space-y-2"><div className="flex items-center justify-between rounded-lg bg-white px-4 py-2"><span className="text-sm text-slate-700">{t.core}</span><span className="text-lg font-semibold text-slate-900">{r.core}</span></div><div className="flex items-center justify-between rounded-lg bg-white px-4 py-2"><span className="text-sm text-slate-700">{t.spouse}</span><span className="text-lg font-semibold text-slate-900">{r.spouse}</span></div><div className="flex items-center justify-between rounded-lg bg-white px-4 py-2"><span className="text-sm text-slate-700">{t.transferability}</span><span className="text-lg font-semibold text-slate-900">{r.transferability}</span></div><div className="flex items-center justify-between rounded-lg bg-white px-4 py-2"><span className="text-sm text-slate-700">{t.additional}</span><span className="text-lg font-semibold text-slate-900">{r.additional}</span></div></div></div>}
</div></div></section>);
}
